name: Upload Firewall Logs to Blob

on:
  schedule:
    # 20th of each month at 12:00 AM IST → UTC = 18:30 on 19th
    - cron: "30 18 19 * *"
  workflow_dispatch: # manual trigger option

jobs:
  upload-logs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Azure Login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Setup Azure CLI
        uses: azure/setup-az@v3

      - name: Upload Monthly Firewall Logs
        run: ./cicd/updated-firewall.sh upload-only
        env:
          AZURE_STORAGE_CONNECTION_STRING: ${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}
