name: Add Database Firewall Rule

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment (dev/qa/prod)'
        required: true
        type: choice
        options:
          - dev
          - qa
          - prod
      developer_name:
        description: 'Developer name (e.g., john-doe)'
        required: true
        type: string
      ip_address:
        description: 'IP address to whitelist (e.g., 203.0.113.45 or 203.0.113.0/24)'
        required: true
        type: string

permissions:
  contents: read

jobs:
  add-firewall-rule:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # --- Azure Login using Service Principal ---
      - name: Azure Login (Service Principal)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}

      - name: Verify Azure Login
        run: az account show

      # --- Set Environment Variables based on input ---
      - name: Set environment variables
        run: |
          case "${{ inputs.environment }}" in
            dev|qa)
              echo "RESOURCE_GROUP=gvk-platform-rg" >> $GITHUB_ENV
              echo "SERVER_NAME=gvk-platform-cosmos" >> $GITHUB_ENV
              ;;
            prod)
              echo "RESOURCE_GROUP=rvc-platform-prod-db-rg" >> $GITHUB_ENV
              echo "SERVER_NAME=rvcplatform-prod-db" >> $GITHUB_ENV
              ;;
            *)
              echo "Invalid environment"
              exit 1
              ;;
          esac
          echo "ENVIRONMENT=${{ inputs.environment }}" >> $GITHUB_ENV

      # --- Add IP to firewall ---
      - name: Add IP to database firewall
        run: |
          set -e
          chmod +x cicd/updated-firewall
          echo "Adding IP ${{ inputs.ip_address }} for developer ${{ inputs.developer_name }} in ${{ inputs.environment }}"
          ./cicd/updated-firewall \
            "${RESOURCE_GROUP}" \
            "${SERVER_NAME}" \
            "${{ inputs.ip_address }}" \
            "${{ inputs.developer_name }}" \
            "${{ inputs.environment }}"

      # --- Display current firewall rules ---
      - name: Display current firewall rules
        run: |
          echo "✅ Successfully added IP ${{ inputs.ip_address }} for ${{ inputs.developer_name }}"
          echo "Current firewall rules for ${SERVER_NAME}:"
          az sql server firewall-rule list \
            --resource-group "${RESOURCE_GROUP}" \
            --server "${SERVER_NAME}" \
            --output table
