name: Add Database Firewall Rule

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment (dev/qa/prod)'
        required: true
        type: choice
        options:
          - dev
          - qa
          - prod
      developer_name:
        description: 'Developer name'
        required: true
        type: string
      ip_address:
        description: 'IP address to whitelist'
        required: true
        type: string

permissions:
  contents: read

jobs:
  add-firewall-rule:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Azure Login (Service Principal)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}

      - name: Verify Azure Login
        run: az account show

      - name: Set environment variables
        run: |
          case "${{ inputs.environment }}" in
            dev|qa)
              echo "RESOURCE_GROUP=gvk-platform-rg" >> $GITHUB_ENV
              echo "SERVER_NAME=gvk-platform-cosmos" >> $GITHUB_ENV
              ;;
            prod)
              echo "RESOURCE_GROUP=rvc-platform-prod-db-rg" >> $GITHUB_ENV
              echo "SERVER_NAME=rvcplatform-prod-db" >> $GITHUB_ENV
              ;;
            *)
              echo "Invalid environment"
              exit 1
              ;;
          esac

      - name: Add IP to database firewall
        run: |
          set -e
          chmod +x cicd/updated-firewal1.sh
          ./cicd/updated-firewal1.sh \
            "${RESOURCE_GROUP}" \
            "${SERVER_NAME}" \
            "${{ inputs.ip_address }}" \
            "${{ inputs.developer_name }}" \
            "${{ inputs.environment }}"

      - name: Display current firewall rules
        run: |
          echo "✅ Successfully added IP ${{ inputs.ip_address }} for ${{ inputs.developer_name }}"
          az sql server firewall-rule list \
            --resource-group "${RESOURCE_GROUP}" \
            --server "${SERVER_NAME}" \
            --output table
